version: "3"

services:
  db:
    build: ./database
    container_name: database-${COMPOSE_PROJECT_NAME}
    expose:
      - ${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_INITDB_ARGS="--locale=ru_RU.utf8"
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
  bot:
    build: ./bot
    container_name: bot-${COMPOSE_PROJECT_NAME}
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE=${DATABASE}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - URL=${URL}
      - CHAT_ID=${CHAT_ID}
      - TOKEN=${TOKEN}
      - INTERVAL=${INTERVAL}
    restart: always
    depends_on:
      - db
