export const SINGLE_IP_REQUESTS_LIMIT = 10;
export const ECONNRESET = 'ECONNRESET';
export const ESOCKETTIMEOUT = 'ESOCKETTIMEDOUT';
export enum TorEvent {
  SESSION_UPDATE_STARTED = 'SESSION_UPDATE_STARTED',
  SESSION_UPDATE_FINISHED = 'SESSION_UPDATE_FINISHED',
  REQUEST_STARTED = 'REQUEST_STARTED',
  REQUEST_FINISHED = 'REQUEST_FINISHED',
  REQUEST_AMOUN_CHANGED = 'REQUEST_AMOUN_CHANGED',
  ALL_REQUESTS_FINISHED = 'ALL_REQUESTS_FINISHED',
}
